# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRxOH0dHyuUvxXAQkQQTcrseZZ8z1HIP
"""

import pandas as pd

# Load the first Excel file
file1 = pd.read_excel('/content/Client List_All_13092023.xlsx', sheet_name='Client List')

# Load the second Excel file
file2 = pd.read_excel('/content/EXPO Real_Exhibitors Directory.xlsx', sheet_name=None)

# Get the first column name in both DataFrames
column_name = file1.columns[0]

# Convert all letters to lowercase in both DataFrames
file1[column_name] = file1[column_name].str.lower()
for sheet_name, df in file2.items():
    file2[sheet_name][column_name] = df.iloc[:, 0].str.lower()

# Create a set of unique lowercase company names from the second file
all_company_names = set()
for df in file2.values():
    all_company_names.update(df[column_name])

# Create a column in the first file to indicate if a company exists in the second file
file1['Exists in Second File'] = file1[column_name].isin(all_company_names)

# Save the updated first file to a new Excel file
file1.to_excel('file1_with_existence.xlsx', index=False)